//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miotsukushi.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miotsukushi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   完了予定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Construction_FinishTime {
            get {
                return ResourceManager.GetString("Construction_FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Construction_Remain {
            get {
                return ResourceManager.GetString("Construction_Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空き に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConstructionStatus_Empty {
            get {
                return ResourceManager.GetString("ConstructionStatus_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロックされています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConstructionStatus_Locked {
            get {
                return ResourceManager.GetString("ConstructionStatus_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込まれていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConstructionStatus_NotLoaded {
            get {
                return ResourceManager.GetString("ConstructionStatus_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConstructionStatus_Unknown {
            get {
                return ResourceManager.GetString("ConstructionStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了予定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Docking_FinishTime {
            get {
                return ResourceManager.GetString("Docking_FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Docking_Remain {
            get {
                return ResourceManager.GetString("Docking_Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空き に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DockingStatus_Empty {
            get {
                return ResourceManager.GetString("DockingStatus_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロックされています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DockingStatus_Locked {
            get {
                return ResourceManager.GetString("DockingStatus_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込まれていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DockingStatus_NotLoaded {
            get {
                return ResourceManager.GetString("DockingStatus_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DockingStatus_Unknown {
            get {
                return ResourceManager.GetString("DockingStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EasyInfoPanelTitle_BuildingDock {
            get {
                return ResourceManager.GetString("EasyInfoPanelTitle_BuildingDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EasyInfoPanelTitle_Expedition {
            get {
                return ResourceManager.GetString("EasyInfoPanelTitle_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   任務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EasyInfoPanelTitle_Quests {
            get {
                return ResourceManager.GetString("EasyInfoPanelTitle_Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EasyInfoPanelTitle_RepairDock {
            get {
                return ResourceManager.GetString("EasyInfoPanelTitle_RepairDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了予定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_FinishTime {
            get {
                return ResourceManager.GetString("Expedition_FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_Remain {
            get {
                return ResourceManager.GetString("Expedition_Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征に出ていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpeditionStatus_AtHome {
            get {
                return ResourceManager.GetString("ExpeditionStatus_AtHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込まれていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpeditionStatus_NotLoaded {
            get {
                return ResourceManager.GetString("ExpeditionStatus_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊が開放されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpeditionStatus_NotOpened {
            get {
                return ResourceManager.GetString("ExpeditionStatus_NotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpeditionStatus_Unknown {
            get {
                return ResourceManager.GetString("ExpeditionStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションを終了してもよろしいですか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowCloseConfirmationMessage {
            get {
                return ResourceManager.GetString("WindowCloseConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowCloseConfirmationTitle {
            get {
                return ResourceManager.GetString("WindowCloseConfirmationTitle", resourceCulture);
            }
        }
    }
}
