//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miotsukushi.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miotsukushi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Finish Time: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Construction_FinishTime {
            get {
                return ResourceManager.GetString("Construction_FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remain: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Construction_Remain {
            get {
                return ResourceManager.GetString("Construction_Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConstructionStatus_Empty {
            get {
                return ResourceManager.GetString("ConstructionStatus_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locked に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConstructionStatus_Locked {
            get {
                return ResourceManager.GetString("ConstructionStatus_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not loaded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConstructionStatus_NotLoaded {
            get {
                return ResourceManager.GetString("ConstructionStatus_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConstructionStatus_Unknown {
            get {
                return ResourceManager.GetString("ConstructionStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finish Time: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Docking_FinishTime {
            get {
                return ResourceManager.GetString("Docking_FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remain: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Docking_Remain {
            get {
                return ResourceManager.GetString("Docking_Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DockingStatus_Empty {
            get {
                return ResourceManager.GetString("DockingStatus_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locked に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DockingStatus_Locked {
            get {
                return ResourceManager.GetString("DockingStatus_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not loaded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DockingStatus_NotLoaded {
            get {
                return ResourceManager.GetString("DockingStatus_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DockingStatus_Unknown {
            get {
                return ResourceManager.GetString("DockingStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Construction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EasyInfoPanelTitle_BuildingDock {
            get {
                return ResourceManager.GetString("EasyInfoPanelTitle_BuildingDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expedition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EasyInfoPanelTitle_Expedition {
            get {
                return ResourceManager.GetString("EasyInfoPanelTitle_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quests に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EasyInfoPanelTitle_Quests {
            get {
                return ResourceManager.GetString("EasyInfoPanelTitle_Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Docking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EasyInfoPanelTitle_RepairDock {
            get {
                return ResourceManager.GetString("EasyInfoPanelTitle_RepairDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finish Time: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_FinishTime {
            get {
                return ResourceManager.GetString("Expedition_FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remain: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_Remain {
            get {
                return ResourceManager.GetString("Expedition_Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not on expedition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpeditionStatus_AtHome {
            get {
                return ResourceManager.GetString("ExpeditionStatus_AtHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not loaded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpeditionStatus_NotLoaded {
            get {
                return ResourceManager.GetString("ExpeditionStatus_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unavailable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpeditionStatus_NotOpened {
            get {
                return ResourceManager.GetString("ExpeditionStatus_NotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpeditionStatus_Unknown {
            get {
                return ResourceManager.GetString("ExpeditionStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Akitsu Maru に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_あきつ丸 {
            get {
                return ResourceManager.GetString("ShipName_あきつ丸", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maruyu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_まるゆ {
            get {
                return ResourceManager.GetString("ShipName_まるゆ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mikazuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_三日月 {
            get {
                return ResourceManager.GetString("ShipName_三日月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mikuma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_三隈 {
            get {
                return ResourceManager.GetString("ShipName_三隈", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shiranui に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_不知火 {
            get {
                return ResourceManager.GetString("ShipName_不知火", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Isuzu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_五十鈴 {
            get {
                return ResourceManager.GetString("ShipName_五十鈴", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Samidare に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_五月雨 {
            get {
                return ResourceManager.GetString("ShipName_五月雨", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I-168 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_伊168 {
            get {
                return ResourceManager.GetString("ShipName_伊168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I-19 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_伊19 {
            get {
                return ResourceManager.GetString("ShipName_伊19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I-401 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_伊401 {
            get {
                return ResourceManager.GetString("ShipName_伊401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I-58 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_伊58 {
            get {
                return ResourceManager.GetString("ShipName_伊58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I-8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_伊8 {
            get {
                return ResourceManager.GetString("ShipName_伊8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ise に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_伊勢 {
            get {
                return ResourceManager.GetString("ShipName_伊勢", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shinano に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_信濃 {
            get {
                return ResourceManager.GetString("ShipName_信濃", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatsuharu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_初春 {
            get {
                return ResourceManager.GetString("ShipName_初春", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatsuyuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_初雪 {
            get {
                return ResourceManager.GetString("ShipName_初雪", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatsushimo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_初霜 {
            get {
                return ResourceManager.GetString("ShipName_初霜", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatsukaze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_初風 {
            get {
                return ResourceManager.GetString("ShipName_初風", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tone に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_利根 {
            get {
                return ResourceManager.GetString("ShipName_利根", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kako に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_加古 {
            get {
                return ResourceManager.GetString("ShipName_加古", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaga に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_加賀 {
            get {
                return ResourceManager.GetString("ShipName_加賀", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kitakami に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_北上 {
            get {
                return ResourceManager.GetString("ShipName_北上", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chiyoda に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_千代田 {
            get {
                return ResourceManager.GetString("ShipName_千代田", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chiyoda A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_千代田甲 {
            get {
                return ResourceManager.GetString("ShipName_千代田甲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chiyoda Carrier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_千代田航 {
            get {
                return ResourceManager.GetString("ShipName_千代田航", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chitose に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_千歳 {
            get {
                return ResourceManager.GetString("ShipName_千歳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chitose A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_千歳甲 {
            get {
                return ResourceManager.GetString("ShipName_千歳甲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chitose Carrier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_千歳航 {
            get {
                return ResourceManager.GetString("ShipName_千歳航", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uzuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_卯月 {
            get {
                return ResourceManager.GetString("ShipName_卯月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Murakumo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_叢雲 {
            get {
                return ResourceManager.GetString("ShipName_叢雲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Furutaka に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_古鷹 {
            get {
                return ResourceManager.GetString("ShipName_古鷹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Natori に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_名取 {
            get {
                return ResourceManager.GetString("ShipName_名取", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fubuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_吹雪 {
            get {
                return ResourceManager.GetString("ShipName_吹雪", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yubari に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_夕張 {
            get {
                return ResourceManager.GetString("ShipName_夕張", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yudachi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_夕立 {
            get {
                return ResourceManager.GetString("ShipName_夕立", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yugumo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_夕雲 {
            get {
                return ResourceManager.GetString("ShipName_夕雲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tama に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_多摩 {
            get {
                return ResourceManager.GetString("ShipName_多摩", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_大井 {
            get {
                return ResourceManager.GetString("ShipName_大井", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yamato に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_大和 {
            get {
                return ResourceManager.GetString("ShipName_大和", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyodo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_大淀 {
            get {
                return ResourceManager.GetString("ShipName_大淀", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oshio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_大潮 {
            get {
                return ResourceManager.GetString("ShipName_大潮", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taigei に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_大鯨 {
            get {
                return ResourceManager.GetString("ShipName_大鯨", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taiho に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_大鳳 {
            get {
                return ResourceManager.GetString("ShipName_大鳳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amatsukaze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_天津風 {
            get {
                return ResourceManager.GetString("ShipName_天津風", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tenryu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_天龍 {
            get {
                return ResourceManager.GetString("ShipName_天龍", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kisaragi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_如月 {
            get {
                return ResourceManager.GetString("ShipName_如月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Myoko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_妙高 {
            get {
                return ResourceManager.GetString("ShipName_妙高", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nenohi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_子日 {
            get {
                return ResourceManager.GetString("ShipName_子日", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yamashiro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_山城 {
            get {
                return ResourceManager.GetString("ShipName_山城", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shimakaze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_島風 {
            get {
                return ResourceManager.GetString("ShipName_島風", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sendai に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_川内 {
            get {
                return ResourceManager.GetString("ShipName_川内", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makigumo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_巻雲 {
            get {
                return ResourceManager.GetString("ShipName_巻雲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yayoi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_弥生 {
            get {
                return ResourceManager.GetString("ShipName_弥生", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Atago に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_愛宕 {
            get {
                return ResourceManager.GetString("ShipName_愛宕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fusou に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_扶桑 {
            get {
                return ResourceManager.GetString("ShipName_扶桑", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maya に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_摩耶 {
            get {
                return ResourceManager.GetString("ShipName_摩耶", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shikinami に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_敷波 {
            get {
                return ResourceManager.GetString("ShipName_敷波", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fumizuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_文月 {
            get {
                return ResourceManager.GetString("ShipName_文月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hyuga に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_日向 {
            get {
                return ResourceManager.GetString("ShipName_日向", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hayashimo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_早霜 {
            get {
                return ResourceManager.GetString("ShipName_早霜", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Akashi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_明石 {
            get {
                return ResourceManager.GetString("ShipName_明石", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Harusame に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_春雨 {
            get {
                return ResourceManager.GetString("ShipName_春雨", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tokitsukaze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_時津風 {
            get {
                return ResourceManager.GetString("ShipName_時津風", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shigure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_時雨 {
            get {
                return ResourceManager.GetString("ShipName_時雨", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Akatsuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_暁 {
            get {
                return ResourceManager.GetString("ShipName_暁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Akebono に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_曙 {
            get {
                return ResourceManager.GetString("ShipName_曙", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mogami に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_最上 {
            get {
                return ResourceManager.GetString("ShipName_最上", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mochizuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_望月 {
            get {
                return ResourceManager.GetString("ShipName_望月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Asashio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_朝潮 {
            get {
                return ResourceManager.GetString("ShipName_朝潮", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oboro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_朧 {
            get {
                return ResourceManager.GetString("ShipName_朧", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kiso に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_木曾 {
            get {
                return ResourceManager.GetString("ShipName_木曾", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Murasame に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_村雨 {
            get {
                return ResourceManager.GetString("ShipName_村雨", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Haruna に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_榛名 {
            get {
                return ResourceManager.GetString("ShipName_榛名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Musashi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_武蔵 {
            get {
                return ResourceManager.GetString("ShipName_武蔵", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiei に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_比叡 {
            get {
                return ResourceManager.GetString("ShipName_比叡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hamakaze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_浜風 {
            get {
                return ResourceManager.GetString("ShipName_浜風", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Urakaze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_浦風 {
            get {
                return ResourceManager.GetString("ShipName_浦風", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suzukaze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_涼風 {
            get {
                return ResourceManager.GetString("ShipName_涼風", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miyuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_深雪 {
            get {
                return ResourceManager.GetString("ShipName_深雪", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kiyoshimo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_清霜 {
            get {
                return ResourceManager.GetString("ShipName_清霜", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Michishio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_満潮 {
            get {
                return ResourceManager.GetString("ShipName_満潮", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sazanami に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_漣 {
            get {
                return ResourceManager.GetString("ShipName_漣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ushio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_潮 {
            get {
                return ResourceManager.GetString("ShipName_潮", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kumano に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_熊野 {
            get {
                return ResourceManager.GetString("ShipName_熊野", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kuma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_球磨 {
            get {
                return ResourceManager.GetString("ShipName_球磨", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zuihou に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_瑞鳳 {
            get {
                return ResourceManager.GetString("ShipName_瑞鳳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zuikaku に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_瑞鶴 {
            get {
                return ResourceManager.GetString("ShipName_瑞鶴", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yura に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_由良 {
            get {
                return ResourceManager.GetString("ShipName_由良", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shirayuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_白雪 {
            get {
                return ResourceManager.GetString("ShipName_白雪", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shiratsuyu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_白露 {
            get {
                return ResourceManager.GetString("ShipName_白露", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satsuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_皐月 {
            get {
                return ResourceManager.GetString("ShipName_皐月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mutsuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_睦月 {
            get {
                return ResourceManager.GetString("ShipName_睦月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yahagi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_矢矧 {
            get {
                return ResourceManager.GetString("ShipName_矢矧", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Isonami に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_磯波 {
            get {
                return ResourceManager.GetString("ShipName_磯波", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Isokaze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_磯風 {
            get {
                return ResourceManager.GetString("ShipName_磯風", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jintsuu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_神通 {
            get {
                return ResourceManager.GetString("ShipName_神通", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shouhou に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_祥鳳 {
            get {
                return ResourceManager.GetString("ShipName_祥鳳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Akizuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_秋月 {
            get {
                return ResourceManager.GetString("ShipName_秋月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Akigumo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_秋雲 {
            get {
                return ResourceManager.GetString("ShipName_秋雲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chikuma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_筑摩 {
            get {
                return ResourceManager.GetString("ShipName_筑摩", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ayanami に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_綾波 {
            get {
                return ResourceManager.GetString("ShipName_綾波", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Haguro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_羽黒 {
            get {
                return ResourceManager.GetString("ShipName_羽黒", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shokaku に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_翔鶴 {
            get {
                return ResourceManager.GetString("ShipName_翔鶴", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Noshiro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_能代 {
            get {
                return ResourceManager.GetString("ShipName_能代", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maikaze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_舞風 {
            get {
                return ResourceManager.GetString("ShipName_舞風", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wakaba に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_若葉 {
            get {
                return ResourceManager.GetString("ShipName_若葉", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arashio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_荒潮 {
            get {
                return ResourceManager.GetString("ShipName_荒潮", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kikuzuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_菊月 {
            get {
                return ResourceManager.GetString("ShipName_菊月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Souryuu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_蒼龍 {
            get {
                return ResourceManager.GetString("ShipName_蒼龍", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kinugasa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_衣笠 {
            get {
                return ResourceManager.GetString("ShipName_衣笠", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tanikaze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_谷風 {
            get {
                return ResourceManager.GetString("ShipName_谷風", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Akagi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_赤城 {
            get {
                return ResourceManager.GetString("ShipName_赤城", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ashigara に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_足柄 {
            get {
                return ResourceManager.GetString("ShipName_足柄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nachi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_那智 {
            get {
                return ResourceManager.GetString("ShipName_那智", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Naka に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_那珂 {
            get {
                return ResourceManager.GetString("ShipName_那珂", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sakawa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_酒匂 {
            get {
                return ResourceManager.GetString("ShipName_酒匂", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kongo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_金剛 {
            get {
                return ResourceManager.GetString("ShipName_金剛", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suzuya に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_鈴谷 {
            get {
                return ResourceManager.GetString("ShipName_鈴谷", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nagatsuki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_長月 {
            get {
                return ResourceManager.GetString("ShipName_長月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Naganami に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_長波 {
            get {
                return ResourceManager.GetString("ShipName_長波", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nagara に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_長良 {
            get {
                return ResourceManager.GetString("ShipName_長良", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nagato に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_長門 {
            get {
                return ResourceManager.GetString("ShipName_長門", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abukuma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_阿武隈 {
            get {
                return ResourceManager.GetString("ShipName_阿武隈", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Agano に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_阿賀野 {
            get {
                return ResourceManager.GetString("ShipName_阿賀野", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mutsu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_陸奥 {
            get {
                return ResourceManager.GetString("ShipName_陸奥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kagerou に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_陽炎 {
            get {
                return ResourceManager.GetString("ShipName_陽炎", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jun&apos;yo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_隼鷹 {
            get {
                return ResourceManager.GetString("ShipName_隼鷹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yukikaze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_雪風 {
            get {
                return ResourceManager.GetString("ShipName_雪風", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unryu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_雲龍 {
            get {
                return ResourceManager.GetString("ShipName_雲龍", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ikazuchi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_雷 {
            get {
                return ResourceManager.GetString("ShipName_雷", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inazuma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_電 {
            get {
                return ResourceManager.GetString("ShipName_電", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kasumi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_霞 {
            get {
                return ResourceManager.GetString("ShipName_霞", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kirishima に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_霧島 {
            get {
                return ResourceManager.GetString("ShipName_霧島", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arare に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_霰 {
            get {
                return ResourceManager.GetString("ShipName_霰", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aoba に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_青葉 {
            get {
                return ResourceManager.GetString("ShipName_青葉", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hibiki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_響 {
            get {
                return ResourceManager.GetString("ShipName_響", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiyo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_飛鷹 {
            get {
                return ResourceManager.GetString("ShipName_飛鷹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiryu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_飛龍 {
            get {
                return ResourceManager.GetString("ShipName_飛龍", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Takao に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_高雄 {
            get {
                return ResourceManager.GetString("ShipName_高雄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kinu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_鬼怒 {
            get {
                return ResourceManager.GetString("ShipName_鬼怒", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chokai に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_鳥海 {
            get {
                return ResourceManager.GetString("ShipName_鳥海", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hosho に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_鳳翔 {
            get {
                return ResourceManager.GetString("ShipName_鳳翔", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kuroshio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_黒潮 {
            get {
                return ResourceManager.GetString("ShipName_黒潮", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tatsuta に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_龍田 {
            get {
                return ResourceManager.GetString("ShipName_龍田", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ryuujou に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_龍驤 {
            get {
                return ResourceManager.GetString("ShipName_龍驤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ryuho に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipName_龍鳳 {
            get {
                return ResourceManager.GetString("ShipName_龍鳳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repair Ship に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_工作艦 {
            get {
                return ResourceManager.GetString("ShipType_工作艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battleship に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_戦艦 {
            get {
                return ResourceManager.GetString("ShipType_戦艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amphibious Assault Ship に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_揚陸艦 {
            get {
                return ResourceManager.GetString("ShipType_揚陸艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fleet Carrier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_正規空母 {
            get {
                return ResourceManager.GetString("ShipType_正規空母", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seaplane Tender に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_水上機母艦 {
            get {
                return ResourceManager.GetString("ShipType_水上機母艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Escort ship に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_海防艦 {
            get {
                return ResourceManager.GetString("ShipType_海防艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submarine Tender に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_潜水母艦 {
            get {
                return ResourceManager.GetString("ShipType_潜水母艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submarine Aircraft Carrier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_潜水空母 {
            get {
                return ResourceManager.GetString("ShipType_潜水空母", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submarine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_潜水艦 {
            get {
                return ResourceManager.GetString("ShipType_潜水艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aviation Cruiser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_航空巡洋艦 {
            get {
                return ResourceManager.GetString("ShipType_航空巡洋艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aviation Battleship に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_航空戦艦 {
            get {
                return ResourceManager.GetString("ShipType_航空戦艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Armored Aircraft Carrier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_装甲空母 {
            get {
                return ResourceManager.GetString("ShipType_装甲空母", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supply Ship に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_補給艦 {
            get {
                return ResourceManager.GetString("ShipType_補給艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Super Dreadnoughts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_超弩級戦艦 {
            get {
                return ResourceManager.GetString("ShipType_超弩級戦艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light Cruiser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_軽巡洋艦 {
            get {
                return ResourceManager.GetString("ShipType_軽巡洋艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light Aircraft Carrier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_軽空母 {
            get {
                return ResourceManager.GetString("ShipType_軽空母", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Heavy Cruiser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_重巡洋艦 {
            get {
                return ResourceManager.GetString("ShipType_重巡洋艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torpedo Cruiser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_重雷装巡洋艦 {
            get {
                return ResourceManager.GetString("ShipType_重雷装巡洋艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destroyer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipType_駆逐艦 {
            get {
                return ResourceManager.GetString("ShipType_駆逐艦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to exit? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowCloseConfirmationMessage {
            get {
                return ResourceManager.GetString("WindowCloseConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowCloseConfirmationTitle {
            get {
                return ResourceManager.GetString("WindowCloseConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Kai に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string 改 {
            get {
                return ResourceManager.GetString("改", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Kai Ni に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string 改二 {
            get {
                return ResourceManager.GetString("改二", resourceCulture);
            }
        }
    }
}
